In [164]:
import pandas as pd
import numpy as np
#df=pd.read_csv("winequality-red.csv",sep=";")
#df
#w=np.loadtxt("winequality-red.csv",delimiter=";",skiprows=1)
#print(w)
wines=np.genfromtxt("winequality-red.csv",delimiter=";",skip_header=1) #genfromtxt directly converts it into array
#wines=np.array(w,dtype="float64")
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [146]:
wines.dtype

dtype('float64')

In [50]:
#wines=np.array(wines,dtype="float64")
#print(wines)

In [119]:
#3.	Identify the shape of the array
wines.shape

(1599, 12)

In [120]:
#4.	Display the element at row 3 and column 4.
wines[2,3]

2.3

In [121]:
#5. Display the first three items from the fourth column.
wines[0:3,3]

array([1.9, 2.6, 2.3])

In [122]:
#6.	Display third column from each row.
wines[:,2]

array([0.  , 0.  , 0.04, ..., 0.13, 0.12, 0.47])

In [123]:
#7.	Display fourth row.
wines[3,:]

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

In [124]:
#8.	Assign value 10 to 2nd row and 6th column element.
wines[1,5]=10
wines[1,5]

10.0

In [134]:
#9.	Take the 10th column from wines array and name that slice as slice_new and assign value 666 to all elements of slice_new.
slice_new=wines[:,9]
print(slice_new)
slice_new[:]=666
print(slice_new)

[0.56 0.68 0.65 ... 0.75 0.71 0.66]
[666. 666. 666. ... 666. 666. 666.]


In [137]:
#10.	Display wines array
np.set_printoptions(suppress=True) #to convert exponential to number
print(wines)

[[  7.4     0.7     0.    ... 666.      9.4     5.   ]
 [  7.8     0.88    0.    ... 666.      9.8     5.   ]
 [  7.8     0.76    0.04  ... 666.      9.8     5.   ]
 ...
 [  6.3     0.51    0.13  ... 666.     11.      6.   ]
 [  5.9     0.645   0.12  ... 666.     10.2     5.   ]
 [  6.      0.31    0.47  ... 666.     11.      6.   ]]


In [128]:
#11.	Find the data type of wines array and Change the data type to int.
print(wines.dtype)
wines=wines.astype(np.int64)
print(wines.dtype)

float64
int64


In [140]:
#12.	Add 10 points to each quality score.
p=wines[:,-1]+10
p

array([15., 15., 15., ..., 16., 15., 16.])

In [105]:
#13.	Find the sum of all the elements in an array
t=np.sum(wines)
t

145524

In [106]:
#14.	Find the sum of all the values in every column.
s=np.sum(wines,axis=0)
s

array([12589,    24,     1,  3350,     0, 25367, 74301,    81,  4770,
          60, 15969,  9012], dtype=int64)

In [107]:
#15.	Find the sum of all the values in every row.
s1=np.sum(wines,axis=1)
s1

array([ 70, 103,  95, ...,  97, 101,  89], dtype=int64)

In [108]:
#16.	Add the quality column to itself.
t1=wines[:,-1]+wines[:,-1]
t1

array([10, 10, 10, ..., 12, 10, 12], dtype=int64)

In [168]:
#17.	Multiply alcohol by quality.
s2=wines[:,-2]*wines[:,-1]
s2

array([47., 49., 49., ..., 66., 51., 66.])

In [192]:
#18.	Display which wines have a quality rating higher than 5.
wines[wines[:,-1]>5,11:12]

array([[6.],
       [7.],
       [7.],
       [7.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [7.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [7.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [7.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [7.],
       [7.],
       [6.],
       [7.],
       [7.],
       [7.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [7.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],

In [191]:
#19.	Check if any wines have a quality rating equal to 10.
wines[wines[:,-1]==10,11:12]

array([], shape=(0, 1), dtype=float64)

In [190]:
#20.	Select rows in wines where the quality is over 7
wines[wines[:,-1]>7,11:12]

array([[8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.]])

In [189]:
#21.	Display wines with alcohol greater than 10 and quality greater than 7.
wines[(wines[:,-2]>10) & (wines[:,-1]>7),10:12]

array([[12.8,  8. ],
       [12.6,  8. ],
       [12.9,  8. ],
       [13.4,  8. ],
       [11.7,  8. ],
       [11. ,  8. ],
       [11. ,  8. ],
       [14. ,  8. ],
       [12.7,  8. ],
       [12.5,  8. ],
       [11.8,  8. ],
       [13.1,  8. ],
       [11.7,  8. ],
       [14. ,  8. ],
       [11.3,  8. ],
       [11.4,  8. ]])

In [193]:
#22.	Change the shape of wines array.
print(wines.shape)
w=wines.reshape((12,1599))
print(w.shape)

(1599, 12)
(12, 1599)


In [72]:
p=pd.read_csv("winequality-red.csv",sep=";")
p

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]