In [45]:
import numpy as np
import pandas as pd

In [82]:
#1.	Down load the dataset winequality-red.csv file( each column is separated by a semicolon (;)) 
#from the UCI Machine Learning Repository
df=np.genfromtxt("winequality-red.csv",delimiter=";",skip_header=True)
df

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [83]:
#2.	Convert it to numPy array, name it as wines (leave the first row of the list) and specify the data type of array as float.
wines=np.array(df)
wines.astype("float64")
wines.dtype

dtype('float64')

In [48]:
#3.	Identify the shape of the array.
wines.shape

(1599, 12)

In [49]:
#4.	Display the element at row 3 and column 4.
wines[2,3]

2.3

In [50]:
#5.	 Display the first three items from the fourth column.
wines[0:3,3]

array([1.9, 2.6, 2.3])

In [51]:
#6.	Display third column from each row.
wines[:,2]

array([0.  , 0.  , 0.04, ..., 0.13, 0.12, 0.47])

In [52]:
#7.	Display fourth row.
wines[3]

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

In [53]:
#8.	Assign value 10 to 2nd row and 6th column element.
print(wines[1,5])
wines[1,5]=10
print(wines[1,5])

25.0
10.0


In [54]:
#9.	Take the 10th column from wines array and name that slice as slice_new and assign value 666 to all elements of slice_new.
slice_new=wines[:,9]
print(slice_new)
slice_new[:]=666
print(slice_new)

[0.56 0.68 0.65 ... 0.75 0.71 0.66]
[666. 666. 666. ... 666. 666. 666.]


In [55]:
#10	Display wines array.
np.set_printoptions(suppress=True)
wines

array([[  7.4  ,   0.7  ,   0.   , ..., 666.   ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ..., 666.   ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ..., 666.   ,   9.8  ,   5.   ],
       ...,
       [  6.3  ,   0.51 ,   0.13 , ..., 666.   ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ..., 666.   ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ..., 666.   ,  11.   ,   6.   ]])

In [56]:
#11.Find the data type of wines array and Change the data type to int.
print(wines.dtype)
wines=wines.astype("int64")
print(wines.dtype)

float64
int64


In [57]:
#12.Add 10 points to each quality score.
t=wines[:,-1]+10
t

array([15, 15, 15, ..., 16, 15, 16], dtype=int64)

In [58]:
#13.Find the sum of all the elements in an array
p=wines.sum()
p

1210398

In [59]:
#14.Find the sum of all the values in every column.
p=wines.sum(axis=0)
p

array([  12589,      24,       1,    3350,       0,   25367,   74301,
            81,    4770, 1064934,   15969,    9012], dtype=int64)

In [63]:
#15.Find the sum of all the values in every row.
p=wines.sum(axis=1)
p

array([736, 769, 761, ..., 763, 767, 755], dtype=int64)

In [64]:
#16.Add the quality column to itself.
t=wines[:,-1]+wines[:,-1]
t

array([10, 10, 10, ..., 12, 10, 12], dtype=int64)

In [65]:
#17.Multiply alcohol by quality.
t=wines[:,-2]*wines[:,-1]
t

array([45, 45, 45, ..., 66, 50, 66], dtype=int64)

In [70]:
#18.Display which wines have a quality rating higher than 5.
wines[wines[:,-1]>5,11:12]

array([[6],
       [7],
       [7],
       [7],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [7],
       [6],
       [6],
       [6],
       [6],
       [6],
       [7],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [7],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [7],
       [7],
       [6],
       [7],
       [7],
       [7],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [7],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [7],
    

In [72]:
#19.Check if any wines have a quality rating equal to 10.
wines[wines[:,-1]==10,11:12]

array([], shape=(0, 1), dtype=int64)

In [71]:
#20.Select rows in wines where the quality is over 7
wines[wines[:,-1]>7,11:12]

array([[8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8]], dtype=int64)

In [75]:
#21.Display wines with alcohol greater than 10 and quality greater than 7.
wines[(wines[:,-2]>10) & (wines[:,-1]>7),10:12]

array([[12,  8],
       [12,  8],
       [12,  8],
       [13,  8],
       [11,  8],
       [11,  8],
       [11,  8],
       [14,  8],
       [12,  8],
       [12,  8],
       [11,  8],
       [13,  8],
       [11,  8],
       [14,  8],
       [11,  8],
       [11,  8]], dtype=int64)

In [84]:
#22.Change the shape of wines array.
print(wines.shape)
wines1=wines.reshape(12,1599)
print(wines1.shape)

(1599, 12)
(12, 1599)
